//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRuleEngine.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyInfo
    {
        public AssemblyInfo()
        {
            this.Action = new HashSet<Action>();
            this.Condition = new HashSet<Condition>();
            this.Vocabulary = new HashSet<Vocabulary>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<Action> Action { get; set; }
        public virtual ICollection<Condition> Condition { get; set; }
        public virtual ICollection<Vocabulary> Vocabulary { get; set; }
    }
}
