//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Column
    {
        public Column()
        {
            this.Column_Tag = new HashSet<Column_Tag>();
            this.RuleOnValue_Column = new HashSet<RuleOnValue_Column>();
            this.RuleOnValue = new HashSet<RuleOnValue>();
            this.RelationshipColumns = new HashSet<RelationshipColumns>();
            this.RelationshipColumns1 = new HashSet<RelationshipColumns>();
            this.TableDrivedEntity = new HashSet<TableDrivedEntity>();
            this.UniqueConstraint = new HashSet<UniqueConstraint>();
        }
    
        public string Value { get; set; }
        public int ID { get; set; }
        public int TableID { get; set; }
        public string Name { get; set; }
        public bool PrimaryKey { get; set; }
        public bool IsIdentity { get; set; }
        public bool IsNull { get; set; }
        public bool IsMandatory { get; set; }
        public string DefaultValue { get; set; }
        public string DataType { get; set; }
        public Nullable<int> Position { get; set; }
        public string Alias { get; set; }
        public bool DataEntryEnabled { get; set; }
        public Nullable<bool> SearchEnabled { get; set; }
        public Nullable<bool> ViewEnabled { get; set; }
    
        public virtual ICollection<Column_Tag> Column_Tag { get; set; }
        public virtual Table Table { get; set; }
        public virtual ColumnKeyValue ColumnKeyValue { get; set; }
        public virtual DateColumnType DateColumnType { get; set; }
        public virtual NumericColumnType NumericColumnType { get; set; }
        public virtual ICollection<RuleOnValue_Column> RuleOnValue_Column { get; set; }
        public virtual ICollection<RuleOnValue> RuleOnValue { get; set; }
        public virtual StringColumnType StringColumnType { get; set; }
        public virtual ICollection<RelationshipColumns> RelationshipColumns { get; set; }
        public virtual ICollection<RelationshipColumns> RelationshipColumns1 { get; set; }
        public virtual ICollection<TableDrivedEntity> TableDrivedEntity { get; set; }
        public virtual ICollection<UniqueConstraint> UniqueConstraint { get; set; }
    }
}
