//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISARelationship
    {
        public ISARelationship()
        {
            this.SubToSuperRelationshipType = new HashSet<SubToSuperRelationshipType>();
            this.SuperToSubRelationshipType = new HashSet<SuperToSubRelationshipType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsGeneralization { get; set; }
        public Nullable<bool> IsSpecialization { get; set; }
        public bool IsTolatParticipation { get; set; }
        public bool IsDisjoint { get; set; }
    
        public virtual ICollection<SubToSuperRelationshipType> SubToSuperRelationshipType { get; set; }
        public virtual ICollection<SuperToSubRelationshipType> SuperToSubRelationshipType { get; set; }
    }
}
