//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public Relationship()
        {
            this.ArcRelationshipGroup_Relationship = new HashSet<ArcRelationshipGroup_Relationship>();
            this.Relationship1 = new HashSet<Relationship>();
            this.RelationshipColumns = new HashSet<RelationshipColumns>();
            this.RuleOnValue_Relationship = new HashSet<RuleOnValue_Relationship>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RelationshipID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> DataEntryEnabled { get; set; }
        public Nullable<bool> SearchEnabled { get; set; }
        public Nullable<bool> ViewEnabled { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public int FirstSideTableID { get; set; }
        public int SecondSideTableID { get; set; }
        public int TableDrivedEntityID1 { get; set; }
        public int TableDrivedEntityID2 { get; set; }
    
        public virtual ICollection<ArcRelationshipGroup_Relationship> ArcRelationshipGroup_Relationship { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity { get; set; }
        public virtual TableDrivedEntity TableDrivedEntity1 { get; set; }
        public virtual ICollection<Relationship> Relationship1 { get; set; }
        public virtual Relationship Relationship2 { get; set; }
        public virtual ICollection<RelationshipColumns> RelationshipColumns { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
        public virtual ICollection<RuleOnValue_Relationship> RuleOnValue_Relationship { get; set; }
    }
}
