//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleOnValue
    {
        public RuleOnValue()
        {
            this.RuleOnValue_Relationship = new HashSet<RuleOnValue_Relationship>();
            this.RuleOnValue_Column = new HashSet<RuleOnValue_Column>();
        }
    
        public int ID { get; set; }
        public int ColumnID { get; set; }
        public string Value { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual ICollection<RuleOnValue_Relationship> RuleOnValue_Relationship { get; set; }
        public virtual ICollection<RuleOnValue_Column> RuleOnValue_Column { get; set; }
    }
}
